apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: infracost-pricing
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/launch-stage: GA
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: infracost-sa@techcyte-infracost-poc.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
        - name: api
          image: REPLACE_API_IMAGE
          env:
            - name: SELF_HOSTED_INFRACOST_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infracost-self-hosted-key
                  key: "latest"          # ⬅ changed from version -> key
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infracost-db-password
                  key: "latest"          # ⬅ same here
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "cloud_pricing"
            - name: POSTGRES_HOST
              value: "127.0.0.1"
          ports:
            - containerPort: 4000

        - name: db
          image: REPLACE_DB_IMAGE
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infracost-db-password
                  key: "latest"          # ⬅ and here
            - name: POSTGRES_DB
              value: "cloud_pricing"
            - name: POSTGRES_USER
              value: "postgres"
